// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0005_user_pato_profile.sql

package database

import (
	"context"
	"database/sql"
)

const createUserPatoProfile = `-- name: CreateUserPatoProfile :execresult
INSERT INTO user_pato_profile (
     us_pt_name, us_pt_avatar, us_pt_phone,
    us_pt_gender, us_pt_address, us_pt_birthday, createdAt
) VALUES (
 ?, ?, ?, ?, ?, ?, NOW()
)
`

type CreateUserPatoProfileParams struct {
	UsPtName     sql.NullString
	UsPtAvatar   sql.NullString
	UsPtPhone    sql.NullString
	UsPtGender   sql.NullString
	UsPtAddress  sql.NullString
	UsPtBirthday sql.NullTime
}

func (q *Queries) CreateUserPatoProfile(ctx context.Context, arg CreateUserPatoProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserPatoProfile,
		arg.UsPtName,
		arg.UsPtAvatar,
		arg.UsPtPhone,
		arg.UsPtGender,
		arg.UsPtAddress,
		arg.UsPtBirthday,
	)
}
