// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0012_operational_costs.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createOperationalCost = `-- name: CreateOperationalCost :execresult
INSERT INTO operational_costs (
    opera_cost_id,opera_cost_res_id, opera_cost_type, opera_cost_amount, opera_cost_description,
    opera_cost_date, opera_cost_status, createdBy, createdAt, updatedAt
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW()
)
`

type CreateOperationalCostParams struct {
	OperaCostID          string
	OperaCostResID       string
	OperaCostType        string
	OperaCostAmount      string
	OperaCostDescription sql.NullString
	OperaCostDate        time.Time
	OperaCostStatus      NullOperationalCostsOperaCostStatus
	Createdby            sql.NullString
}

func (q *Queries) CreateOperationalCost(ctx context.Context, arg CreateOperationalCostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOperationalCost,
		arg.OperaCostID,
		arg.OperaCostResID,
		arg.OperaCostType,
		arg.OperaCostAmount,
		arg.OperaCostDescription,
		arg.OperaCostDate,
		arg.OperaCostStatus,
		arg.Createdby,
	)
}

const deleteOperationalCost = `-- name: DeleteOperationalCost :exec
UPDATE operational_costs
SET isDeleted = 1, deletedAt = NOW(), deletedBy = ?
WHERE opera_cost_id = ? AND opera_cost_res_id = ?
`

type DeleteOperationalCostParams struct {
	Deletedby      sql.NullString
	OperaCostID    string
	OperaCostResID string
}

func (q *Queries) DeleteOperationalCost(ctx context.Context, arg DeleteOperationalCostParams) error {
	_, err := q.db.ExecContext(ctx, deleteOperationalCost, arg.Deletedby, arg.OperaCostID, arg.OperaCostResID)
	return err
}

const getListOperationalCosts = `-- name: GetListOperationalCosts :many
WITH total_count AS (
    SELECT COUNT(*) AS total FROM operational_costs
    WHERE operational_costs.isDeleted = ? AND operational_costs.opera_cost_type LIKE ? AND operational_costs.opera_cost_res_id = ?
)
SELECT 
    opera_cost_id, opera_cost_type, opera_cost_amount, opera_cost_date, opera_cost_status,
    (SELECT total FROM total_count) AS total_items,
    COALESCE(CEIL((SELECT total FROM total_count) / NULLIF(CAST(? AS FLOAT), 0)), 0) AS total_pages
FROM operational_costs
WHERE operational_costs.isDeleted = ? AND operational_costs.opera_cost_type LIKE ? AND operational_costs.opera_cost_res_id = ?
LIMIT ? OFFSET ?
`

type GetListOperationalCostsParams struct {
	Isdeleted        sql.NullInt32
	OperaCostType    string
	OperaCostResID   string
	Column4          float64
	Isdeleted_2      sql.NullInt32
	OperaCostType_2  string
	OperaCostResID_2 string
	Limit            int32
	Offset           int32
}

type GetListOperationalCostsRow struct {
	OperaCostID     string
	OperaCostType   string
	OperaCostAmount string
	OperaCostDate   time.Time
	OperaCostStatus NullOperationalCostsOperaCostStatus
	TotalItems      int64
	TotalPages      interface{}
}

func (q *Queries) GetListOperationalCosts(ctx context.Context, arg GetListOperationalCostsParams) ([]GetListOperationalCostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getListOperationalCosts,
		arg.Isdeleted,
		arg.OperaCostType,
		arg.OperaCostResID,
		arg.Column4,
		arg.Isdeleted_2,
		arg.OperaCostType_2,
		arg.OperaCostResID_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListOperationalCostsRow
	for rows.Next() {
		var i GetListOperationalCostsRow
		if err := rows.Scan(
			&i.OperaCostID,
			&i.OperaCostType,
			&i.OperaCostAmount,
			&i.OperaCostDate,
			&i.OperaCostStatus,
			&i.TotalItems,
			&i.TotalPages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOperationalCost = `-- name: GetOperationalCost :one
SELECT opera_cost_id, opera_cost_type, opera_cost_amount, opera_cost_description,
       opera_cost_date, opera_cost_status, isDeleted
FROM operational_costs
WHERE opera_cost_id = ? AND opera_cost_res_id = ?
`

type GetOperationalCostParams struct {
	OperaCostID    string
	OperaCostResID string
}

type GetOperationalCostRow struct {
	OperaCostID          string
	OperaCostType        string
	OperaCostAmount      string
	OperaCostDescription sql.NullString
	OperaCostDate        time.Time
	OperaCostStatus      NullOperationalCostsOperaCostStatus
	Isdeleted            sql.NullInt32
}

func (q *Queries) GetOperationalCost(ctx context.Context, arg GetOperationalCostParams) (GetOperationalCostRow, error) {
	row := q.db.QueryRowContext(ctx, getOperationalCost, arg.OperaCostID, arg.OperaCostResID)
	var i GetOperationalCostRow
	err := row.Scan(
		&i.OperaCostID,
		&i.OperaCostType,
		&i.OperaCostAmount,
		&i.OperaCostDescription,
		&i.OperaCostDate,
		&i.OperaCostStatus,
		&i.Isdeleted,
	)
	return i, err
}

const restoreOperationalCost = `-- name: RestoreOperationalCost :exec
UPDATE operational_costs
SET isDeleted = 0, deletedAt = NULL, deletedBy = NULL
WHERE opera_cost_id = ? AND opera_cost_res_id = ?
`

type RestoreOperationalCostParams struct {
	OperaCostID    string
	OperaCostResID string
}

func (q *Queries) RestoreOperationalCost(ctx context.Context, arg RestoreOperationalCostParams) error {
	_, err := q.db.ExecContext(ctx, restoreOperationalCost, arg.OperaCostID, arg.OperaCostResID)
	return err
}

const updateOperationalCost = `-- name: UpdateOperationalCost :exec
UPDATE operational_costs
SET opera_cost_type = ?, opera_cost_amount = ?, opera_cost_description = ?, opera_cost_date = ?,
    updatedAt = NOW(), updatedBy = ?
WHERE opera_cost_id = ? AND opera_cost_res_id = ?
`

type UpdateOperationalCostParams struct {
	OperaCostType        string
	OperaCostAmount      string
	OperaCostDescription sql.NullString
	OperaCostDate        time.Time
	Updatedby            sql.NullString
	OperaCostID          string
	OperaCostResID       string
}

func (q *Queries) UpdateOperationalCost(ctx context.Context, arg UpdateOperationalCostParams) error {
	_, err := q.db.ExecContext(ctx, updateOperationalCost,
		arg.OperaCostType,
		arg.OperaCostAmount,
		arg.OperaCostDescription,
		arg.OperaCostDate,
		arg.Updatedby,
		arg.OperaCostID,
		arg.OperaCostResID,
	)
	return err
}

const updateOperationalCostStatus = `-- name: UpdateOperationalCostStatus :exec
UPDATE operational_costs
SET opera_cost_status = ?, updatedAt = NOW(), updatedBy = ?
WHERE opera_cost_id = ? AND opera_cost_res_id = ?
`

type UpdateOperationalCostStatusParams struct {
	OperaCostStatus NullOperationalCostsOperaCostStatus
	Updatedby       sql.NullString
	OperaCostID     string
	OperaCostResID  string
}

func (q *Queries) UpdateOperationalCostStatus(ctx context.Context, arg UpdateOperationalCostStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOperationalCostStatus,
		arg.OperaCostStatus,
		arg.Updatedby,
		arg.OperaCostID,
		arg.OperaCostResID,
	)
	return err
}
