// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type PreGoAccUserTwoFactor9999TwoFactorAuthType string

const (
	PreGoAccUserTwoFactor9999TwoFactorAuthTypeSMS   PreGoAccUserTwoFactor9999TwoFactorAuthType = "SMS"
	PreGoAccUserTwoFactor9999TwoFactorAuthTypeEMAIL PreGoAccUserTwoFactor9999TwoFactorAuthType = "EMAIL"
	PreGoAccUserTwoFactor9999TwoFactorAuthTypeAPP   PreGoAccUserTwoFactor9999TwoFactorAuthType = "APP"
)

func (e *PreGoAccUserTwoFactor9999TwoFactorAuthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PreGoAccUserTwoFactor9999TwoFactorAuthType(s)
	case string:
		*e = PreGoAccUserTwoFactor9999TwoFactorAuthType(s)
	default:
		return fmt.Errorf("unsupported scan type for PreGoAccUserTwoFactor9999TwoFactorAuthType: %T", src)
	}
	return nil
}

type NullPreGoAccUserTwoFactor9999TwoFactorAuthType struct {
	PreGoAccUserTwoFactor9999TwoFactorAuthType PreGoAccUserTwoFactor9999TwoFactorAuthType
	Valid                                      bool // Valid is true if PreGoAccUserTwoFactor9999TwoFactorAuthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPreGoAccUserTwoFactor9999TwoFactorAuthType) Scan(value interface{}) error {
	if value == nil {
		ns.PreGoAccUserTwoFactor9999TwoFactorAuthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PreGoAccUserTwoFactor9999TwoFactorAuthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPreGoAccUserTwoFactor9999TwoFactorAuthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PreGoAccUserTwoFactor9999TwoFactorAuthType), nil
}

// blog
type Blog struct {
	BlID          string
	CatBlID       string
	BlTitle       string
	BlDescription sql.NullString
	BlSlug        string
	BlImage       sql.NullString
	BlContent     string
	// 0: Bản nháp, 1: chờ duyệt, 2: Từ chối duyệt, 3 đợi xuất bản, 4: lên lịch xuất bản, 5: Đã xuất bản, 6: Không xuất bản
	BlStatus sql.NullInt32
	// 0: Bài viết, 1: Video, 3: Ảnh
	BlType              sql.NullInt32
	BlView              sql.NullInt32
	BlPublishedTime     sql.NullTime
	BlPublishedSchedule sql.NullTime
	Createdat           sql.NullTime
	Updatedat           sql.NullTime
	Deletedat           sql.NullTime
	Createdby           sql.NullString
	Updatedby           sql.NullString
	Deletedby           sql.NullString
	// 0: chưa xóa, 1: đã xóa
	Isdeleted sql.NullInt32
}

// blog_note
type BlogNote struct {
	BlNoteID  string
	BlID      string
	BlContent string
}

// blog_related
type BlogRelated struct {
	BlID    string
	BlRltID string
}

// category_blog
type CategoryBlog struct {
	CatBlID          string
	CatBlName        string
	CatBlDescription sql.NullString
	CatBlSlug        string
	CatBlOrder       sql.NullInt32
	// 0: inactive, 1: active
	CatBlStatus sql.NullInt32
	Createdat   sql.NullTime
	Updatedat   sql.NullTime
	Deletedat   sql.NullTime
	Createdby   sql.NullString
	Updatedby   sql.NullString
	Deletedby   sql.NullString
	// 0: chưa xóa, 1: đã xóa
	Isdeleted sql.NullInt32
}

// pre_go_acc_user_base_9999
type PreGoAccUserBase9999 struct {
	UserID         int32
	UserAccount    string
	UserPassword   string
	UserSalt       string
	UserLoginTime  sql.NullTime
	UserLogoutTime sql.NullTime
	UserLoginIp    sql.NullString
	UserCreatedAt  sql.NullTime
	UserUpdatedAt  sql.NullTime
	// authentication is enabled for the user
	IsTwoFactorEnabled sql.NullInt32
}

// pre_go_acc_user_info_9999
type PreGoAccUserInfo9999 struct {
	// User ID
	UserID uint64
	// User account
	UserAccount string
	// User nickname
	UserNickname sql.NullString
	// User avatar
	UserAvatar sql.NullString
	// User state: 0-Locked, 1-Activated, 2-Not Activated
	UserState uint8
	// Mobile phone number
	UserMobile sql.NullString
	// User gender: 0-Secret, 1-Male, 2-Female
	UserGender sql.NullInt16
	// User birthday
	UserBirthday sql.NullTime
	// User email address
	UserEmail sql.NullString
	// Authentication status: 0-Not Authenticated, 1-Pending, 2-Authenticated, 3-Failed
	UserIsAuthentication uint8
	// Record creation time
	CreatedAt sql.NullTime
	// Record update time
	UpdatedAt sql.NullTime
}

// pre_go_acc_user_two_factor_9999
type PreGoAccUserTwoFactor9999 struct {
	TwoFactorID         uint32
	UserID              uint32
	TwoFactorAuthType   PreGoAccUserTwoFactor9999TwoFactorAuthType
	TwoFactorAuthSecret string
	TwoFactorPhone      sql.NullString
	TwoFactorEmail      sql.NullString
	TwoFactorIsActive   bool
	TwoFactorCreatedAt  sql.NullTime
	TwoFactorUpdatedAt  sql.NullTime
}

// account_user_verify
type PreGoAccUserVerify9999 struct {
	VerifyID        int32
	VerifyOtp       string
	VerifyKey       string
	VerifyKeyHash   string
	VerifyType      sql.NullInt32
	IsVerified      sql.NullInt32
	IsDeleted       sql.NullInt32
	VerifyCreatedAt sql.NullTime
	VerifyUpdatedAt sql.NullTime
}

// system_parameters
type SystemParameter struct {
	SysParaID          string
	SysParaDescription sql.NullString
	SysParaValue       string
	Createdat          sql.NullTime
	Updatedat          sql.NullTime
	Createdby          sql.NullString
	Updatedby          sql.NullString
}

// user_management_account
type UserManagementAccount struct {
	UsaID              string
	UsaEmail           string
	UsaSalt            string
	UsaPassword        string
	UsaActiveTime      sql.NullTime
	UsaLockedTime      sql.NullTime
	UsaRecoverPassTime sql.NullTime
	UsaVerifyTime      sql.NullTime
	UsaVerifyCode      sql.NullString
	UsaRecoverPassCode sql.NullString
	// 0: kích hoạt
	UsaActive sql.NullInt32
	UsaLocked sql.NullInt32
	Createdat sql.NullTime
	Updatedat sql.NullTime
	Deletedat sql.NullTime
	Createdby sql.NullString
	Updatedby sql.NullString
	Deletedby sql.NullString
	// 0: chưa xóa, 1: đã xóa
	Isdeleted sql.NullInt32
}

// user_management_account
type UserManagementProfile struct {
	UsID       string
	UsName     sql.NullString
	UsAvatar   sql.NullString
	UsPhone    sql.NullString
	UsGender   sql.NullString
	UsAddress  sql.NullString
	UsBirthday sql.NullTime
	Createdat  sql.NullTime
	Updatedat  sql.NullTime
	Deletedat  sql.NullTime
	Createdby  sql.NullString
	Updatedby  sql.NullString
	Deletedby  sql.NullString
	// 0: chưa xóa, 1: đã xóa
	Isdeleted sql.NullInt32
}

// user_management_session
type UserManagementSession struct {
	UssID         string
	UsaID         string
	UssRf         string
	UssKeyAt      string
	UssKeyRf      string
	UssClientID   string
	UssLoginTime  time.Time
	UssLogoutTime sql.NullTime
	Createdat     sql.NullTime
	Updatedat     sql.NullTime
	Deletedat     sql.NullTime
	Createdby     sql.NullString
	Updatedby     sql.NullString
}
