// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/ducvubo",
        "contact": {
            "name": "Vũ Đức Bo",
            "url": "https://github.com/ducvubo",
            "email": "vminhduc8@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/equipment-maintenance": {
            "get": {
                "description": "GetAllEquipmentMaintenance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipment Maintenance"
                ],
                "summary": "GetAllEquipmentMaintenance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "EqpMtnName",
                        "name": "EqpMtnName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "description": "CreateEquipmentMaintenance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipment Maintenance"
                ],
                "summary": "CreateEquipmentMaintenance",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateEquipmentMaintenanceDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "patch": {
                "description": "UpdateEquipmentMaintenance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipment Maintenance"
                ],
                "summary": "UpdateEquipmentMaintenance",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateEquipmentMaintenanceDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/equipment-maintenance/recycle": {
            "get": {
                "description": "GetAllEquipmentMaintenanceRecycle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipment Maintenance"
                ],
                "summary": "GetAllEquipmentMaintenanceRecycle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "EqpMtnName",
                        "name": "EqpMtnName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/equipment-maintenance/restore/{id}": {
            "patch": {
                "description": "RestoreEquipmentMaintenance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipment Maintenance"
                ],
                "summary": "RestoreEquipmentMaintenance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/equipment-maintenance/update-status": {
            "patch": {
                "description": "UpdateEquipmentMaintenanceStatus",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipment Maintenance"
                ],
                "summary": "UpdateEquipmentMaintenanceStatus",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateEquipmentMaintenanceStatusDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/equipment-maintenance/{id}": {
            "get": {
                "description": "FindEquipmentMaintenance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipment Maintenance"
                ],
                "summary": "FindEquipmentMaintenance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "description": "DeleteEquipmentMaintenance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipment Maintenance"
                ],
                "summary": "DeleteEquipmentMaintenance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/internal-note": {
            "get": {
                "description": "GetAllInternalNote",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Note"
                ],
                "summary": "GetAllInternalNote",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ItnNoteTitle",
                        "name": "ItnNoteTitle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "description": "CreateInternalNote",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Note"
                ],
                "summary": "CreateInternalNote",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateInternalNoteDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "patch": {
                "description": "UpdateInternalNote",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Note"
                ],
                "summary": "UpdateInternalNote",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateInternalNoteDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/internal-note/recycle": {
            "get": {
                "description": "GetAllInternalNoteRecycle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Note"
                ],
                "summary": "GetAllInternalNoteRecycle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ItnNoteTitle",
                        "name": "ItnNoteTitle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/internal-note/restore/{id}": {
            "patch": {
                "description": "RestoreInternalNote",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Note"
                ],
                "summary": "RestoreInternalNote",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/internal-note/{id}": {
            "get": {
                "description": "FindInternalNote",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Note"
                ],
                "summary": "FindInternalNote",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "description": "DeleteInternalNote",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Note"
                ],
                "summary": "DeleteInternalNote",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/internal-proposal": {
            "get": {
                "description": "GetAllInternalProposal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Proposal"
                ],
                "summary": "GetAllInternalProposal",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ItnProposalTitle",
                        "name": "ItnProposalTitle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "description": "CreateInternalProposal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Proposal"
                ],
                "summary": "CreateInternalProposal",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateInternalProposalDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "patch": {
                "description": "UpdateInternalProposal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Proposal"
                ],
                "summary": "UpdateInternalProposal",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateInternalProposalDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/internal-proposal/recycle": {
            "get": {
                "description": "GetAllInternalProposalRecycle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Proposal"
                ],
                "summary": "GetAllInternalProposalRecycle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ItnProposalTitle",
                        "name": "ItnProposalTitle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/internal-proposal/restore/{id}": {
            "patch": {
                "description": "RestoreInternalProposal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Proposal"
                ],
                "summary": "RestoreInternalProposal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/internal-proposal/update-status": {
            "patch": {
                "description": "UpdateInternalProposalStatus",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Proposal"
                ],
                "summary": "UpdateInternalProposalStatus",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateInternalProposalStatusDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/internal-proposal/{id}": {
            "get": {
                "description": "FindInternalProposal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Proposal"
                ],
                "summary": "FindInternalProposal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "description": "DeleteInternalProposal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal Proposal"
                ],
                "summary": "DeleteInternalProposal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/operation-manual": {
            "get": {
                "description": "GetAllOperationManual",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operation Manual"
                ],
                "summary": "GetAllOperationManual",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "OperaManualTitle",
                        "name": "OperaManualTitle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "description": "CreateOperationManual",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operation Manual"
                ],
                "summary": "CreateOperationManual",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateOperationManualDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "patch": {
                "description": "UpdateOperationManual",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operation Manual"
                ],
                "summary": "UpdateOperationManual",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateOperationManualDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/operation-manual/recycle": {
            "get": {
                "description": "GetAllOperationManualRecycle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operation Manual"
                ],
                "summary": "GetAllOperationManualRecycle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "OperaManualTitle",
                        "name": "OperaManualTitle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/operation-manual/restore/{id}": {
            "patch": {
                "description": "RestoreOperationManual",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operation Manual"
                ],
                "summary": "RestoreOperationManual",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/operation-manual/update-status": {
            "patch": {
                "description": "UpdateOperationManualStatus",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operation Manual"
                ],
                "summary": "UpdateOperationManualStatus",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateOperationManualStatusDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/operation-manual/{id}": {
            "get": {
                "description": "FindOperationManual",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operation Manual"
                ],
                "summary": "FindOperationManual",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "description": "DeleteOperationManual",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operation Manual"
                ],
                "summary": "DeleteOperationManual",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/operational-costs": {
            "get": {
                "description": "GetAllOperationalCosts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operational Costs"
                ],
                "summary": "GetAllOperationalCosts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "OperaCostType",
                        "name": "OperaCostType",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "description": "CreateOperationalCosts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operational Costs"
                ],
                "summary": "CreateOperationalCosts",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateOperationalCostsDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "patch": {
                "description": "UpdateOperationalCosts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operational Costs"
                ],
                "summary": "UpdateOperationalCosts",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateOperationalCostsDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/operational-costs/recycle": {
            "get": {
                "description": "GetAllOperationalCostsRecycle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operational Costs"
                ],
                "summary": "GetAllOperationalCostsRecycle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "OperaCostType",
                        "name": "OperaCostType",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/operational-costs/restore/{id}": {
            "patch": {
                "description": "RestoreOperationalCosts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operational Costs"
                ],
                "summary": "RestoreOperationalCosts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/operational-costs/update-status": {
            "patch": {
                "description": "UpdateOperationalCostsStatus",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operational Costs"
                ],
                "summary": "UpdateOperationalCostsStatus",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateOperationalCostsStatusDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/operational-costs/{id}": {
            "get": {
                "description": "FindOperationalCosts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operational Costs"
                ],
                "summary": "FindOperationalCosts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "description": "DeleteOperationalCosts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operational Costs"
                ],
                "summary": "DeleteOperationalCosts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/system-parameter": {
            "get": {
                "description": "GetAllSystemParameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System Parameter"
                ],
                "summary": "GetAllSystemParameter",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/system-parameter/save": {
            "post": {
                "description": "SaveSystemParameterDto",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System Parameter"
                ],
                "summary": "SaveSystemParameterDto",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SaveSystemParameterDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/system-parameter/{sysParaID}": {
            "get": {
                "description": "GetSystemParameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System Parameter"
                ],
                "summary": "GetSystemParameter",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sysParaID",
                        "name": "sysParaID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "Upload an image file to Cloudinary with a specified folder from header and return original and transformed URLs",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File Upload"
                ],
                "summary": "Upload a file to Cloudinary",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload (jpg, jpeg, png, gif)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Folder name in Cloudinary (optional)",
                        "name": "folder",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upload successful with original and transformed file URLs",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/upload.ImageResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid file or request",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "500": {
                        "description": "Server or Cloudinary error",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-account": {
            "post": {
                "description": "CreateUserManagementAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Account"
                ],
                "summary": "CreateUserManagementAccount",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateUserManagementAccountDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-account/login": {
            "post": {
                "description": "LoginUserManagementAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Account"
                ],
                "summary": "LoginUserManagementAccount",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginUserManagementAccountDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-account/profile": {
            "get": {
                "description": "GetProfileUser",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Account"
                ],
                "summary": "GetProfileUser",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-account/refresh-token": {
            "post": {
                "description": "RefreshToken",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Account"
                ],
                "summary": "RefreshToken",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-profile": {
            "get": {
                "description": "GetAllUserManagementProfile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "GetAllUserManagementProfile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "usName",
                        "name": "usName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "description": "CreateUserManagementProfile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "CreateUserManagementProfile",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateUserManagementProfileDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "patch": {
                "description": "UpdateUserManagementProfile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "UpdateUserManagementProfile",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateUserManagementProfileDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-profile/recycle": {
            "get": {
                "description": "GetAllUserManagementProfileRecycle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "GetAllUserManagementProfileRecycle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "usName",
                        "name": "usName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-profile/restore/{id}": {
            "patch": {
                "description": "RestoreUserManagementProfile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "RestoreUserManagementProfile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-profile/{id}": {
            "get": {
                "description": "FindUserManagementProfile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "FindUserManagementProfile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "description": "DeleteUserManagementProfile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "DeleteUserManagementProfile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-pato-account/activate-account": {
            "post": {
                "description": "ActivateAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Pato Account"
                ],
                "summary": "ActivateAccount",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ActiveAccountDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-pato-account/login": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Pato Account"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginUserPatoAccountDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-pato-account/register": {
            "post": {
                "description": "CreateUserPatoAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Pato Account"
                ],
                "summary": "CreateUserPatoAccount",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RegisterUserPatoAccountDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-pato-account/resend-otp": {
            "post": {
                "description": "ResendOtp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Pato Account"
                ],
                "summary": "ResendOtp",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ResendOtpDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ActiveAccountDto": {
            "type": "object",
            "required": [
                "us_pt_email",
                "us_pt_otp"
            ],
            "properties": {
                "us_pt_email": {
                    "type": "string"
                },
                "us_pt_otp": {
                    "type": "integer"
                }
            }
        },
        "model.CreateEquipmentMaintenanceDto": {
            "type": "object",
            "required": [
                "eqp_mtn_date_reported",
                "eqp_mtn_name"
            ],
            "properties": {
                "eqp_mtn_cost": {
                    "type": "integer"
                },
                "eqp_mtn_date_fixed": {
                    "type": "string"
                },
                "eqp_mtn_date_reported": {
                    "type": "string"
                },
                "eqp_mtn_issue_description": {
                    "type": "string"
                },
                "eqp_mtn_location": {
                    "type": "string"
                },
                "eqp_mtn_name": {
                    "type": "string"
                },
                "eqp_mtn_note": {
                    "type": "string"
                },
                "eqp_mtn_performed_by": {
                    "type": "string"
                },
                "eqp_mtn_reported_by": {
                    "type": "string"
                }
            }
        },
        "model.CreateInternalNoteDto": {
            "type": "object",
            "required": [
                "itn_note_content",
                "itn_note_title",
                "itn_note_type"
            ],
            "properties": {
                "itn_note_content": {
                    "type": "string"
                },
                "itn_note_title": {
                    "type": "string"
                },
                "itn_note_type": {
                    "type": "string"
                }
            }
        },
        "model.CreateInternalProposalDto": {
            "type": "object",
            "required": [
                "itn_proposal_content",
                "itn_proposal_title",
                "itn_proposal_type"
            ],
            "properties": {
                "itn_proposal_content": {
                    "type": "string"
                },
                "itn_proposal_title": {
                    "type": "string"
                },
                "itn_proposal_type": {
                    "type": "string"
                }
            }
        },
        "model.CreateOperationManualDto": {
            "type": "object",
            "required": [
                "opera_manual_content",
                "opera_manual_title",
                "opera_manual_type"
            ],
            "properties": {
                "opera_manual_content": {
                    "type": "string"
                },
                "opera_manual_note": {
                    "type": "string"
                },
                "opera_manual_title": {
                    "type": "string"
                },
                "opera_manual_type": {
                    "type": "string"
                }
            }
        },
        "model.CreateOperationalCostsDto": {
            "type": "object",
            "required": [
                "opera_cost_amount",
                "opera_cost_date",
                "opera_cost_description",
                "opera_cost_type"
            ],
            "properties": {
                "opera_cost_amount": {
                    "type": "integer"
                },
                "opera_cost_date": {
                    "type": "string"
                },
                "opera_cost_description": {
                    "type": "string"
                },
                "opera_cost_type": {
                    "type": "string"
                }
            }
        },
        "model.CreateUserManagementAccountDto": {
            "type": "object",
            "required": [
                "us_email",
                "us_id",
                "us_pass"
            ],
            "properties": {
                "us_email": {
                    "type": "string"
                },
                "us_id": {
                    "type": "string"
                },
                "us_pass": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                }
            }
        },
        "model.CreateUserManagementProfileDto": {
            "type": "object",
            "required": [
                "us_address",
                "us_avatar",
                "us_birthday",
                "us_gender",
                "us_name",
                "us_phone"
            ],
            "properties": {
                "us_address": {
                    "type": "string"
                },
                "us_avatar": {
                    "type": "string"
                },
                "us_birthday": {
                    "type": "string"
                },
                "us_gender": {
                    "type": "string"
                },
                "us_name": {
                    "type": "string"
                },
                "us_phone": {
                    "type": "string"
                }
            }
        },
        "model.LoginUserManagementAccountDto": {
            "type": "object",
            "required": [
                "us_email",
                "us_pass"
            ],
            "properties": {
                "us_email": {
                    "type": "string"
                },
                "us_pass": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                }
            }
        },
        "model.LoginUserPatoAccountDto": {
            "type": "object",
            "required": [
                "us_pt_email",
                "us_pt_pass"
            ],
            "properties": {
                "us_pt_email": {
                    "type": "string"
                },
                "us_pt_pass": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                }
            }
        },
        "model.RegisterUserPatoAccountDto": {
            "type": "object",
            "required": [
                "url_redirect",
                "us_pt_email",
                "us_pt_pass"
            ],
            "properties": {
                "url_redirect": {
                    "type": "string"
                },
                "us_pt_email": {
                    "type": "string"
                },
                "us_pt_pass": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                }
            }
        },
        "model.ResendOtpDto": {
            "type": "object",
            "required": [
                "url_redirect",
                "us_pt_email"
            ],
            "properties": {
                "url_redirect": {
                    "type": "string"
                },
                "us_pt_email": {
                    "type": "string"
                }
            }
        },
        "model.SaveSystemParameterDto": {
            "type": "object",
            "required": [
                "sys_para_description",
                "sys_para_id",
                "sys_para_value"
            ],
            "properties": {
                "sys_para_description": {
                    "type": "string"
                },
                "sys_para_id": {
                    "type": "string"
                },
                "sys_para_value": {
                    "type": "string"
                }
            }
        },
        "model.UpdateEquipmentMaintenanceDto": {
            "type": "object",
            "required": [
                "eqp_mtn_date_reported",
                "eqp_mtn_id",
                "eqp_mtn_name"
            ],
            "properties": {
                "eqp_mtn_cost": {
                    "type": "integer"
                },
                "eqp_mtn_date_fixed": {
                    "type": "string"
                },
                "eqp_mtn_date_reported": {
                    "type": "string"
                },
                "eqp_mtn_id": {
                    "type": "string"
                },
                "eqp_mtn_issue_description": {
                    "type": "string"
                },
                "eqp_mtn_location": {
                    "type": "string"
                },
                "eqp_mtn_name": {
                    "type": "string"
                },
                "eqp_mtn_note": {
                    "type": "string"
                },
                "eqp_mtn_performed_by": {
                    "type": "string"
                },
                "eqp_mtn_reported_by": {
                    "type": "string"
                }
            }
        },
        "model.UpdateEquipmentMaintenanceStatusDto": {
            "type": "object",
            "required": [
                "eqp_mtn_id",
                "eqp_mtn_status"
            ],
            "properties": {
                "eqp_mtn_id": {
                    "type": "string"
                },
                "eqp_mtn_status": {
                    "description": "ENUM: pending, in_progress, done, rejected",
                    "type": "string"
                }
            }
        },
        "model.UpdateInternalNoteDto": {
            "type": "object",
            "required": [
                "itn_note_content",
                "itn_note_id",
                "itn_note_title",
                "itn_note_type"
            ],
            "properties": {
                "itn_note_content": {
                    "type": "string"
                },
                "itn_note_id": {
                    "type": "string"
                },
                "itn_note_title": {
                    "type": "string"
                },
                "itn_note_type": {
                    "type": "string"
                }
            }
        },
        "model.UpdateInternalProposalDto": {
            "type": "object",
            "required": [
                "itn_proposal_content",
                "itn_proposal_id",
                "itn_proposal_title",
                "itn_proposal_type"
            ],
            "properties": {
                "itn_proposal_content": {
                    "type": "string"
                },
                "itn_proposal_id": {
                    "type": "string"
                },
                "itn_proposal_title": {
                    "type": "string"
                },
                "itn_proposal_type": {
                    "type": "string"
                }
            }
        },
        "model.UpdateInternalProposalStatusDto": {
            "type": "object",
            "required": [
                "itn_proposal_id",
                "itn_proposal_status"
            ],
            "properties": {
                "itn_proposal_id": {
                    "type": "string"
                },
                "itn_proposal_status": {
                    "type": "string"
                }
            }
        },
        "model.UpdateOperationManualDto": {
            "type": "object",
            "required": [
                "opera_manual_content",
                "opera_manual_id",
                "opera_manual_note",
                "opera_manual_title",
                "opera_manual_type"
            ],
            "properties": {
                "opera_manual_content": {
                    "type": "string"
                },
                "opera_manual_id": {
                    "type": "string"
                },
                "opera_manual_note": {
                    "type": "string"
                },
                "opera_manual_title": {
                    "type": "string"
                },
                "opera_manual_type": {
                    "type": "string"
                }
            }
        },
        "model.UpdateOperationManualStatusDto": {
            "type": "object",
            "required": [
                "opera_manual_id",
                "opera_manual_status"
            ],
            "properties": {
                "opera_manual_id": {
                    "type": "string"
                },
                "opera_manual_status": {
                    "type": "string"
                }
            }
        },
        "model.UpdateOperationalCostsDto": {
            "type": "object",
            "required": [
                "opera_cost_amount",
                "opera_cost_date",
                "opera_cost_description",
                "opera_cost_id",
                "opera_cost_type"
            ],
            "properties": {
                "opera_cost_amount": {
                    "type": "integer"
                },
                "opera_cost_date": {
                    "type": "string"
                },
                "opera_cost_description": {
                    "type": "string"
                },
                "opera_cost_id": {
                    "type": "string"
                },
                "opera_cost_type": {
                    "type": "string"
                }
            }
        },
        "model.UpdateOperationalCostsStatusDto": {
            "type": "object",
            "required": [
                "opera_cost_id",
                "opera_cost_status"
            ],
            "properties": {
                "opera_cost_id": {
                    "type": "string"
                },
                "opera_cost_status": {
                    "description": "ENUM: pending, in_progress, done, rejected",
                    "type": "string"
                }
            }
        },
        "model.UpdateUserManagementProfileDto": {
            "type": "object",
            "required": [
                "us_address",
                "us_avatar",
                "us_birthday",
                "us_gender",
                "us_id",
                "us_name",
                "us_phone"
            ],
            "properties": {
                "us_address": {
                    "type": "string"
                },
                "us_avatar": {
                    "type": "string"
                },
                "us_birthday": {
                    "type": "string"
                },
                "us_gender": {
                    "type": "string"
                },
                "us_id": {
                    "type": "string"
                },
                "us_name": {
                    "type": "string"
                },
                "us_phone": {
                    "type": "string"
                }
            }
        },
        "response.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "status code",
                    "type": "integer"
                },
                "data": {
                    "description": "dữ liệu trả về"
                },
                "error": {
                    "description": "dữ liệu lỗi"
                },
                "message": {
                    "description": "thông báo lỗi"
                },
                "statusCode": {
                    "description": "HTTP status code",
                    "type": "integer"
                }
            }
        },
        "upload.ImageResponse": {
            "type": "object",
            "properties": {
                "image_cloud": {
                    "type": "string"
                },
                "image_custom": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "AccessTokenAuth": {
            "type": "apiKey",
            "name": "x-at-tk",
            "in": "header"
        },
        "ClientIDAuth": {
            "type": "apiKey",
            "name": "id_user_guest",
            "in": "header"
        },
        "RefreshTokenAuth": {
            "type": "apiKey",
            "name": "x-rf-tk",
            "in": "header"
        }
    },
    "security": [
        {
            "ClientIDAuth": []
        },
        {
            "AccessTokenAuth": []
        },
        {
            "RefreshTokenAuth": []
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "system.management.pg.taphoaictu.id.vn",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API Documentation System Management",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
