// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/ducvubo",
        "contact": {
            "name": "Vũ Đức Bo",
            "url": "https://github.com/ducvubo",
            "email": "vminhduc8@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/system-parameter": {
            "get": {
                "description": "GetAllSystemParameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System Parameter"
                ],
                "summary": "GetAllSystemParameter",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/system-parameter/save": {
            "post": {
                "description": "SaveSystemParameterDto",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System Parameter"
                ],
                "summary": "SaveSystemParameterDto",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SaveSystemParameterDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/system-parameter/{sysParaID}": {
            "get": {
                "description": "GetSystemParameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System Parameter"
                ],
                "summary": "GetSystemParameter",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sysParaID",
                        "name": "sysParaID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "Upload an image file to Cloudinary with a specified folder from header and return original and transformed URLs",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File Upload"
                ],
                "summary": "Upload a file to Cloudinary",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload (jpg, jpeg, png, gif)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Folder name in Cloudinary (optional)",
                        "name": "folder",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upload successful with original and transformed file URLs",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/upload.ImageResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid file or request",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "500": {
                        "description": "Server or Cloudinary error",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-account": {
            "post": {
                "description": "CreateUserManagementAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Account"
                ],
                "summary": "CreateUserManagementAccount",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateUserManagementAccountDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-account/login": {
            "post": {
                "description": "LoginUserManagementAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Account"
                ],
                "summary": "LoginUserManagementAccount",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginUserManagementAccountDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-account/profile": {
            "get": {
                "description": "GetProfileUser",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Account"
                ],
                "summary": "GetProfileUser",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-account/refresh-token": {
            "post": {
                "description": "RefreshToken",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Account"
                ],
                "summary": "RefreshToken",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-profile": {
            "get": {
                "description": "GetAllUserManagementProfile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "GetAllUserManagementProfile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "usName",
                        "name": "usName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "description": "CreateUserManagementProfile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "CreateUserManagementProfile",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateUserManagementProfileDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "patch": {
                "description": "UpdateUserManagementProfile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "UpdateUserManagementProfile",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateUserManagementProfileDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-profile/recycle": {
            "get": {
                "description": "GetAllUserManagementProfileRecycle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "GetAllUserManagementProfileRecycle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageIndex",
                        "name": "pageIndex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "usName",
                        "name": "usName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-profile/restore/{id}": {
            "patch": {
                "description": "RestoreUserManagementProfile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "RestoreUserManagementProfile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-management-profile/{id}": {
            "get": {
                "description": "FindUserManagementProfile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "FindUserManagementProfile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "description": "DeleteUserManagementProfile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management Profile"
                ],
                "summary": "DeleteUserManagementProfile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-pato-account/activate-account": {
            "post": {
                "description": "ActivateAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Pato Account"
                ],
                "summary": "ActivateAccount",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ActiveAccountDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-pato-account/login": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Pato Account"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginUserPatoAccountDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-pato-account/register": {
            "post": {
                "description": "CreateUserPatoAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Pato Account"
                ],
                "summary": "CreateUserPatoAccount",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RegisterUserPatoAccountDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/user-pato-account/resend-otp": {
            "post": {
                "description": "ResendOtp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Pato Account"
                ],
                "summary": "ResendOtp",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ResendOtpDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ActiveAccountDto": {
            "type": "object",
            "required": [
                "us_pt_email",
                "us_pt_otp"
            ],
            "properties": {
                "us_pt_email": {
                    "type": "string"
                },
                "us_pt_otp": {
                    "type": "integer"
                }
            }
        },
        "model.CreateUserManagementAccountDto": {
            "type": "object",
            "required": [
                "us_email",
                "us_id",
                "us_pass"
            ],
            "properties": {
                "us_email": {
                    "type": "string"
                },
                "us_id": {
                    "type": "string"
                },
                "us_pass": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                }
            }
        },
        "model.CreateUserManagementProfileDto": {
            "type": "object",
            "required": [
                "us_address",
                "us_avatar",
                "us_birthday",
                "us_gender",
                "us_name",
                "us_phone"
            ],
            "properties": {
                "us_address": {
                    "type": "string"
                },
                "us_avatar": {
                    "type": "string"
                },
                "us_birthday": {
                    "type": "string"
                },
                "us_gender": {
                    "type": "string"
                },
                "us_name": {
                    "type": "string"
                },
                "us_phone": {
                    "type": "string"
                }
            }
        },
        "model.LoginUserManagementAccountDto": {
            "type": "object",
            "required": [
                "us_email",
                "us_pass"
            ],
            "properties": {
                "us_email": {
                    "type": "string"
                },
                "us_pass": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                }
            }
        },
        "model.LoginUserPatoAccountDto": {
            "type": "object",
            "required": [
                "us_pt_email",
                "us_pt_pass"
            ],
            "properties": {
                "us_pt_email": {
                    "type": "string"
                },
                "us_pt_pass": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                }
            }
        },
        "model.RegisterUserPatoAccountDto": {
            "type": "object",
            "required": [
                "url_redirect",
                "us_pt_email",
                "us_pt_pass"
            ],
            "properties": {
                "url_redirect": {
                    "type": "string"
                },
                "us_pt_email": {
                    "type": "string"
                },
                "us_pt_pass": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                }
            }
        },
        "model.ResendOtpDto": {
            "type": "object",
            "required": [
                "url_redirect",
                "us_pt_email"
            ],
            "properties": {
                "url_redirect": {
                    "type": "string"
                },
                "us_pt_email": {
                    "type": "string"
                }
            }
        },
        "model.SaveSystemParameterDto": {
            "type": "object",
            "required": [
                "sys_para_description",
                "sys_para_id",
                "sys_para_value"
            ],
            "properties": {
                "sys_para_description": {
                    "type": "string"
                },
                "sys_para_id": {
                    "type": "string"
                },
                "sys_para_value": {
                    "type": "string"
                }
            }
        },
        "model.UpdateUserManagementProfileDto": {
            "type": "object",
            "required": [
                "us_address",
                "us_avatar",
                "us_birthday",
                "us_gender",
                "us_id",
                "us_name",
                "us_phone"
            ],
            "properties": {
                "us_address": {
                    "type": "string"
                },
                "us_avatar": {
                    "type": "string"
                },
                "us_birthday": {
                    "type": "string"
                },
                "us_gender": {
                    "type": "string"
                },
                "us_id": {
                    "type": "string"
                },
                "us_name": {
                    "type": "string"
                },
                "us_phone": {
                    "type": "string"
                }
            }
        },
        "response.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "status code",
                    "type": "integer"
                },
                "data": {
                    "description": "dữ liệu trả về"
                },
                "error": {
                    "description": "dữ liệu lỗi"
                },
                "message": {
                    "description": "thông báo lỗi"
                },
                "statusCode": {
                    "description": "HTTP status code",
                    "type": "integer"
                }
            }
        },
        "upload.ImageResponse": {
            "type": "object",
            "properties": {
                "image_cloud": {
                    "type": "string"
                },
                "image_custom": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "AccessTokenAuth": {
            "type": "apiKey",
            "name": "x-at-tk",
            "in": "header"
        },
        "ClientIDAuth": {
            "type": "apiKey",
            "name": "id_user_guest",
            "in": "header"
        },
        "RefreshTokenAuth": {
            "type": "apiKey",
            "name": "x-rf-tk",
            "in": "header"
        }
    },
    "security": [
        {
            "ClientIDAuth": []
        },
        {
            "AccessTokenAuth": []
        },
        {
            "RefreshTokenAuth": []
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:13000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API Documentation System Management",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
