server:
  port: 13000
  mode: "dev"
mysql:
  host: 160.191.245.32
  port: 30316
  username: root
  password: Duc17052003*
  dbname: SystemManagementPG
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
redis:
  host: 160.187.229.179
  port: 6379 
  password: mypassword
  database: 0
  user: myusername
jwt:
  TOKEN_HOUR_LIFESPAN: 1
  JWT_EXPIRATION: 1h
  API_SECRET: "xxx.yyy.zzz"
